version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 4

  - package-ecosystem: gomod
    directory: /pkgs/policy-checker
    schedule:
      interval: weekly
    cooldown:
      default-days: 4
