# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

keys:
  # users
  - &flokli age1lvpj49ewyx9a4uxevl05wfevmqld2d25juc65acjqpmerzdpc9kq2kxdgs
  - &hrosten age1hc6hszepd5xezxkgd3yx74pn3scxjm5w6px48m4rq9yj7w6rke7q72zhgn
  - &jrautiola age1hszrldafdz09hzze4lgq58r0r66p4sjftn6q8z6h0leer77jhf4qd9vu9v
  - &vjuntunen age194hljejmy63ph884cnuuume7z33txlkp9an7l3yt2n3sjjere52qkvlfju
  - &cazfi age10a2kt6f07urjv6ahutda3jgr73wferkcqjhkvukwm07eaaqyrqtsh08syf
  - &fayad age18t3gss4l6l629rd8s93eh3ctycu9vjnsftehy38c8tstu2gqycxs64t4sw
  - &ktu age1czt3ddm0wngf6h6aj0es8d4kh6y7tx7fflf2dfeafmy7apwyr59qw3rcza

  # hosts
  - &binarycache age1s47a3y44j695gemcl0kqgjlxxvaa50de9s69jy2l6vc8xtmk5pcskhpknl
  - &monitoring age17s9sc2cgt9t30cyl65zya8p4zmwnndrx2r896e7gzgl08sjn0qmq3t6shs
  - &testagent-prod age12nrv5a9rk9vqvx2tqvghn4kt9ps6gdszmmynhjegl2ewefkh03fsexuy9y
  - &testagent-dev age1qjhxuh80tg2vq32kmwu2ne4vqvd8q2up7css30x0yefkrhq9jd0sxju3fa
  - &testagent-release age1pkd7crz3c0axuy4nnesjjzmklmqptx9fq5v8ndjevfgr5lqg8cgskhfyt7
  - &build1 age15xx3qgw69hsmjyw64zmh9q0akyl3mh73dtvmdvhgezplqwaprstqffth7g
  - &build2 age123c6y9ws4za8xzc5wtm20gfsv2exfp69tvfmzcsu7l377u7s89tq8ymhc3
  - &build3 age1q7c2wlrpj0dvthdg7v9j4jmee0kzda8ggtp4nq8jay9u4catee3sn9pa0w
  - &build4 age146j4dfg9974kxe8hegjrdq5ywaldxw5j3fnkghxc6jkrrf0tndpsjjs0x3
  - &hetzarm age1ppunea05ue028qezt9rvhp59dgcskkleetyjpqtxzea7vtp4ppfqh7ltuy
  - &hetz86-1 age1zy44vwv4t97fhaupczfu835t6lfssxhzd6sfu7vlmel5gfrg4gxq6j5egr
  - &hetz86-builder age13p9uu27kv9qchcxy6dd8s602fep5zk3xqe8pwhe7yqaa5hyj697qhax6g8
  - &hetzci-release age19kx56nu8rlwtyaap83vyg940ylv9hpf7dprgdpcctqqv8k8ecqhsnxtfs4
  - &hetzci-prod age1av993eefvndhv2apa4x7tpc7ezyhuj3jz9866vtulnrdwmjqe5hqrjc2z8
  - &hetzci-dev age10xhyyjrhackyac2f042t3z8yqld3sh39ul3mukwkt6gyr7gn9upq8n30gm
  - &hetzci-vm age1lur2w9nehe2thcjrnddh554gygncs8dynv0fmr74sgytd69qqcdsr42d8j
  - &ghaf-log age15kk5q4u68pfsy5auzah6klsdk6p50jnkr986u7vpzfrnj30pz4ssq7wnud
  - &ghaf-webserver age1f643hcr8xvzm6fha93xhn6dw552tfd6zvu7eulxk7vedgt09d9ysljsayq
  - &ghaf-proxy age1sv50w7ydcqxxng4nfpvretqhusfkjewtrzpu4006z685xgplha2sa9tv9v
  - &ghaf-auth age1xuynsp2q9cj0h7f3syha7p7n8t034m2u8qldn6zlwx4nee8d5chskr4el7
  - &ghaf-monitoring age1g2g220kp8p47al7w3jdqtpyw77u5pgc8ntz2zu50uez76vj7agtqqwwpyd
  - &testagent-uae-dev age1sl8yrksst9aq2fhg8t8h7tysgzm6ks00n9hxsvj8x6frsnrskd4szerqez

creation_rules:
  - path_regex: hosts/binarycache/secrets.yaml$
    key_groups:
    - age:
      - *binarycache
      - *jrautiola
      - *hrosten
  - path_regex: hosts/monitoring/secrets.yaml$
    key_groups:
    - age:
      - *monitoring
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/testagent/prod/secrets.yaml$
    key_groups:
    - age:
      - *testagent-prod
      - *jrautiola
      - *flokli
      - *vjuntunen
      - *hrosten
  - path_regex: hosts/testagent/dev/secrets.yaml$
    key_groups:
    - age:
      - *testagent-dev
      - *jrautiola
      - *vjuntunen
      - *hrosten
  - path_regex: hosts/testagent/release/secrets.yaml$
    key_groups:
    - age:
      - *testagent-release
      - *jrautiola
      - *vjuntunen
      - *hrosten
  - path_regex: hosts/builders/build1/secrets.yaml$
    key_groups:
    - age:
      - *build1
      - *hrosten
      - *jrautiola
      - *fayad
  - path_regex: hosts/builders/build2/secrets.yaml$
    key_groups:
    - age:
      - *build2
      - *hrosten
      - *jrautiola
      - *fayad
  - path_regex: hosts/builders/build3/secrets.yaml$
    key_groups:
    - age:
      - *build3
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/builders/build4/secrets.yaml$
    key_groups:
    - age:
      - *build4
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/builders/hetzarm/secrets.yaml$
    key_groups:
    - age:
      - *hetzarm
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/builders/hetz86-1/secrets.yaml$
    key_groups:
    - age:
      - *hetz86-1
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/builders/hetz86-builder/secrets.yaml$
    key_groups:
    - age:
      - *hetz86-builder
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/ghaf-log/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-log
      - *jrautiola
      - *hrosten
  - path_regex: hosts/ghaf-proxy/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-proxy
      - *jrautiola
      - *fayad
      - *hrosten
  - path_regex: hosts/ghaf-monitoring/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-monitoring
      - *jrautiola
      - *fayad
      - *hrosten
  - path_regex: hosts/ghaf-webserver/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-webserver
      - *cazfi
  - path_regex: hosts/ghaf-auth/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-auth
      - *jrautiola
      - *hrosten
      - *fayad
  - path_regex: hosts/hetzci/release/secrets.yaml$
    key_groups:
    - age:
      - *hetzci-release
      - *hrosten
      - *jrautiola
  - path_regex: hosts/hetzci/prod/secrets.yaml$
    key_groups:
    - age:
      - *hetzci-prod
      - *hrosten
      - *jrautiola
  - path_regex: hosts/hetzci/dev/secrets.yaml$
    key_groups:
    - age:
      - *hetzci-dev
      - *hrosten
      - *jrautiola
  - path_regex: hosts/hetzci/vm/secrets.yaml$
    key_groups:
    - age:
      - *hetzci-vm
      - *hrosten
      - *jrautiola
      - *vjuntunen
      - *fayad
      - *cazfi
      - *ktu
  - path_regex: hosts/testagent/credentials.yaml$
    key_groups:
    - age:
      - *testagent-dev
      - *testagent-prod
      - *testagent-release
      - *testagent-uae-dev
      - *jrautiola
      - *vjuntunen
      - *fayad
      - *hrosten
  - path_regex: hosts/testagent/uae-dev/secrets.yaml$
    key_groups:
    - age:
      - *testagent-uae-dev
      - *fayad
      - *vjuntunen
      - *jrautiola
      - *hrosten
  - path_regex: terraform/terraform-secrets.yaml$
    key_groups:
    - age:
      - *fayad
      - *vjuntunen
      - *jrautiola
      - *hrosten
      - *cazfi
      - *flokli
      - *ktu
