# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

keys:
  # users
  - &flokli age1lvpj49ewyx9a4uxevl05wfevmqld2d25juc65acjqpmerzdpc9kq2kxdgs
  - &hrosten age1hc6hszepd5xezxkgd3yx74pn3scxjm5w6px48m4rq9yj7w6rke7q72zhgn
  - &jrautiola age1hszrldafdz09hzze4lgq58r0r66p4sjftn6q8z6h0leer77jhf4qd9vu9v
  - &vjuntunen age194hljejmy63ph884cnuuume7z33txlkp9an7l3yt2n3sjjere52qkvlfju
  - &cazfi age10a2kt6f07urjv6ahutda3jgr73wferkcqjhkvukwm07eaaqyrqtsh08syf
  - &fayad age18t3gss4l6l629rd8s93eh3ctycu9vjnsftehy38c8tstu2gqycxs64t4sw

  # hosts
  - &binarycache age1s47a3y44j695gemcl0kqgjlxxvaa50de9s69jy2l6vc8xtmk5pcskhpknl
  - &monitoring age17s9sc2cgt9t30cyl65zya8p4zmwnndrx2r896e7gzgl08sjn0qmq3t6shs
  - &testagent-prod age12nrv5a9rk9vqvx2tqvghn4kt9ps6gdszmmynhjegl2ewefkh03fsexuy9y
  - &testagent-dev age1qjhxuh80tg2vq32kmwu2ne4vqvd8q2up7css30x0yefkrhq9jd0sxju3fa
  - &testagent-release age1pkd7crz3c0axuy4nnesjjzmklmqptx9fq5v8ndjevfgr5lqg8cgskhfyt7
  - &build3 age1q7c2wlrpj0dvthdg7v9j4jmee0kzda8ggtp4nq8jay9u4catee3sn9pa0w
  - &hetzarm age1ppunea05ue028qezt9rvhp59dgcskkleetyjpqtxzea7vtp4ppfqh7ltuy
  - &ghaf-log age15kk5q4u68pfsy5auzah6klsdk6p50jnkr986u7vpzfrnj30pz4ssq7wnud
  - &ghaf-coverity age1z825k99myjmfcml86pujcmtj96psvj8c3m08me8kkq03tkpwy9xql4jt9y
  - &ghaf-webserver age1f643hcr8xvzm6fha93xhn6dw552tfd6zvu7eulxk7vedgt09d9ysljsayq
  - &ghaf-proxy age1sv50w7ydcqxxng4nfpvretqhusfkjewtrzpu4006z685xgplha2sa9tv9v
  - &testagent-uae-dev age1sl8yrksst9aq2fhg8t8h7tysgzm6ks00n9hxsvj8x6frsnrskd4szerqez

creation_rules:
  - path_regex: hosts/binarycache/secrets.yaml$
    key_groups:
    - age:
      - *binarycache
      - *jrautiola
  - path_regex: hosts/monitoring/secrets.yaml$
    key_groups:
    - age:
      - *monitoring
      - *jrautiola
  - path_regex: hosts/testagent/prod/secrets.yaml$
    key_groups:
    - age:
      - *testagent-prod
      - *jrautiola
      - *flokli
      - *vjuntunen
  - path_regex: hosts/testagent/dev/secrets.yaml$
    key_groups:
    - age:
      - *testagent-dev
      - *jrautiola
      - *vjuntunen
  - path_regex: hosts/testagent/release/secrets.yaml$
    key_groups:
    - age:
      - *testagent-release
      - *jrautiola
      - *vjuntunen
  - path_regex: hosts/builders/build3/secrets.yaml$
    key_groups:
    - age:
      - *build3
      - *jrautiola
  - path_regex: hosts/builders/hetzarm/secrets.yaml$
    key_groups:
    - age:
      - *hetzarm
      - *jrautiola
  - path_regex: hosts/ghaf-log/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-log
      - *jrautiola
  - path_regex: hosts/ghaf-coverity/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-coverity
      - *jrautiola
      - *fayad
  - path_regex: hosts/ghaf-proxy/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-proxy
      - *jrautiola
      - *fayad
  - path_regex: hosts/ghaf-webserver/secrets.yaml$
    key_groups:
    - age:
      - *ghaf-webserver
      - *cazfi
  - path_regex: hosts/testagent/credentials.yaml$
    key_groups:
    - age:
      - *testagent-dev
      - *testagent-prod
      - *testagent-release
      - *testagent-uae-dev
      - *jrautiola
      - *vjuntunen
      - *fayad
  - path_regex: hosts/testagent/uae-dev/secrets.yaml$
    key_groups:
    - age:
      - *testagent-uae-dev
      - *fayad
      - *vjuntunen
      - *jrautiola
