# SPDX-FileCopyrightText: 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "ghaf-infra"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf-infra"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2025 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  "flake.lock",
  "**.patch",
  "**.yaml",
  "**/provider.tf",
  "**/backend.tf",
  "**/plugins.nix",
  "**/plugins.toml",
]
