# TODO: sort out jenkins authentication e.g.:
# https://plugins.jenkins.io/github-oauth/
# Below config requires admin to trigger builds or manage jenkins
# allowing read access for anonymous users:

jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  - name: "lenovo-x1"
  - name: "nuc"
  - name: "orin-agx"
  - name: "orin-nx"
  - name: "riscv"

  nodes:
  - permanent:
      launcher: "inbound"
      mode: EXCLUSIVE
      name: "lenovo-x1"
      remoteFS: "/var/lib/jenkins/agents/lenovo-x1"
      retentionStrategy: "always"
  - permanent:
      launcher: "inbound"
      mode: EXCLUSIVE
      name: "nuc"
      remoteFS: "/var/lib/jenkins/agents/nuc"
      retentionStrategy: "always"
  - permanent:
      launcher: "inbound"
      mode: EXCLUSIVE
      name: "orin-agx"
      remoteFS: "/var/lib/jenkins/agents/orin-agx"
      retentionStrategy: "always"
  - permanent:
      launcher: "inbound"
      mode: EXCLUSIVE
      name: "orin-nx"
      remoteFS: "/var/lib/jenkins/agents/orin-nx"
      retentionStrategy: "always"
  - permanent:
      launcher: "inbound"
      mode: EXCLUSIVE
      name: "riscv"
      remoteFS: "/var/lib/jenkins/agents/riscv"
      retentionStrategy: "always"

  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - diskSpaceMonitor:
      freeSpaceThreshold: "1GB"
  - tmpSpace:
      freeSpaceThreshold: "1GB"
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "myView"
        - "timezone"
        - "experimentalFlags"
        - "mailer"
        - "favorite"
        - preferredProvider:
            providerId: "default"
  slaveAgentPort: -1
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "${file:/var/lib/jenkins-casc/url}"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
# https://github.com/jenkinsci/job-dsl-plugin
# https://jenkinsci.github.io/job-dsl-plugin
jobs:
  - script: >
      pipelineJob('Ghaf main pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-main-pipeline.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Ghaf pre-merge pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-pre-merge-pipeline.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Ghaf nightly pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-nightly-pipeline.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Ghaf release pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-release-pipeline.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Ghaf HW test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-hw-test.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Ghaf parallel HW test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("ghaf-parallel-hw-test.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('FMO OS main_pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/tiiuae/ghaf-jenkins-pipeline.git')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                }
              }
              scriptPath("fmo-os-main-pipeline.groovy")
            }
            lightweight()
          }
        }
      }
  - script: >
      queue('Ghaf main pipeline')
  - script: >
      queue('Ghaf pre-merge pipeline')
  - script: >
      queue('Ghaf nightly pipeline')
  - script: >
      queue('Ghaf release pipeline')
  - script: >
      queue('FMO OS main_pipeline')
