{
 "title": "Nebula",
 "description": "Monitor system metrics for Nebula application performance with this Grafana dashboard. Track main hosts count, network packets lost, garbage collections, memory usage, and more to ensure optimal system operation.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connected hosts count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nebula_hostmap_main_hosts", "legendFormat": "{{machine_name}}" }
   ]
  },
  {
   "title": "Network Packets Lost",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(machine_name) (increase(nebula_network_packets_lost[$__range]))",
     "legendFormat": "{{machine_name}}"
    }
   ]
  },
  {
   "title": "Certificate TTL",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nebula_certificate_ttl_seconds", "legendFormat": "{{machine_name}}" }
   ]
  },
  {
   "title": "Requests dropped by firewall rules",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "increase(nebula_firewall_incoming_dropped_local_addr[$__rate_interval]) + increase(nebula_firewall_incoming_dropped_no_rule[$__rate_interval]) + increase(nebula_firewall_incoming_dropped_remote_addr[$__rate_interval])",
     "legendFormat": "{{machine_name}} Incoming"
    },
    {
     "expr": "increase(nebula_firewall_outgoing_dropped_local_addr[$__rate_interval]) + (increase(nebula_firewall_outgoing_dropped_no_rule[$__rate_interval])) + (increase(nebula_firewall_outgoing_dropped_remote_addr[$__rate_interval]))",
     "legendFormat": "{{machine_name}} Outgoing"
    }
   ]
  },
  {
   "title": "Handshakes timing",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "nebula_handshakes{type=\"mean\"}",
     "legendFormat": "{{machine_name}} Mean"
    },
    {
     "expr": "nebula_handshakes{type=\"perc95\"}",
     "legendFormat": "{{machine_name}} perc95"
    }
   ]
  },
  {
   "title": "Messages TX Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nebula_messages_tx_recv_error", "legendFormat": "{{machine_name}}" }
   ]
  },
  {
   "title": "Total Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nebula_runtime_MemStats_Alloc", "legendFormat": "{{machine_name}}" }
   ]
  }
 ]
}