{
 "title": "SSH connections",
 "description": "Loki v2/v3 SSH Logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Opened Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |= `session opened for` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Opened connections per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |= `session opened for` [1h]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "SSH Recent Log",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"$job\", host=~\"$host\", unit=\"sshd.service\"}"
    }
   ]
  },
  {
   "title": "Session Opened by User",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(username) (count_over_time({job=~\"$job\", host=~\"$host\", unit=\"sshd.service\"} |= `session opened for` | pattern `<_> session opened for user <username>(` | __error__=`` [$__auto]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Session Opened by Unique IP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(ip) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `Accepted .* for` | pattern `Accepted <_> for <_> from <ip> port <_>` | __error__=`` [$__auto]))",
     "legendFormat": "{{ ip }}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Total Failed Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `Failed|Invalid|Connection closed by .* user` [$__auto]))"
    }
   ]
  },
  {
   "title": "Failed connections per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `Failed|Invalid|Connection closed by .* user` [1h]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Failed Attempt by User",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(username) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `Disconnected from .* user` | pattern `<_> user <username> <_> port` [$__auto]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Failed by Unique IP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `no matching host key` | pattern `<_> negotiate with <ip> port <_>` | __error__=`` [$__auto]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({unit=\"sshd.service\", job=~\"$job\", host=~\"$host\"} |~ `Disconnected from .* user` | pattern `<_> user <_> <ip> port <_>` | __error__=`` [$__auto]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Fail2Ban recent activity",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{job=~\"$job\", host=~\"$host\", unit=\"fail2ban.service\"} |= `NOTICE`"
    }
   ]
  }
 ]
}