jenkins:

  authorizationStrategy: unsecured

  numExecutors: 4

  # allow html in build description for artifacts link
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true

unclassified:
  timestamper:
    allPipelines: true

jobs:
  - script: >
      def pipeline = new File("/etc/jenkins/pipelines/ghaf-demo-nix-build.groovy");
      if (pipeline.exists()) {
        pipelineJob('ghaf-demo-nix-build') {
          definition {
            cps {
              script(pipeline.text)
              sandbox()
            }
          }
        }
      }
