appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true

jenkins:
  authorizationStrategy:
    globalMatrix:
      entries:
        - group:
            name: authenticated
            permissions:
              - Overall/Read
              - Job/Read
        - group:
            name: 'tiiuae:devenv-fi'
            permissions:
              - Overall/Administer
        - group:
            name: testagents
            permissions:
              - Agent/Connect
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  nodes:
    - permanent:
        labelString: lenovo-x1
        launcher: inbound
        mode: EXCLUSIVE
        name: release-lenovo-x1
        remoteFS: /var/lib/jenkins/agents/lenovo-x1
        retentionStrategy: always
    - permanent:
        labelString: nuc
        launcher: inbound
        mode: EXCLUSIVE
        name: release-nuc
        remoteFS: /var/lib/jenkins/agents/nuc
        retentionStrategy: always
    - permanent:
        labelString: orin-agx
        launcher: inbound
        mode: EXCLUSIVE
        name: release-orin-agx
        remoteFS: /var/lib/jenkins/agents/orin-agx
        retentionStrategy: always
    - permanent:
        labelString: orin-nx
        launcher: inbound
        mode: EXCLUSIVE
        name: release-orin-nx
        remoteFS: /var/lib/jenkins/agents/orin-nx
        retentionStrategy: always
    - permanent:
        labelString: dell-7330
        launcher: inbound
        mode: EXCLUSIVE
        name: release-dell-7330
        remoteFS: /var/lib/jenkins/agents/dell-7330
        retentionStrategy: always
  numExecutors: 4
  securityRealm:
    reverseProxy:
      customLogOutUrl: /oauth2/sign_out
      disableLdapEmailResolver: true
      forwardedDisplayName: X-Forwarded-DisplayName
      forwardedEmail: X-Forwarded-Mail
      forwardedUser: X-Forwarded-User
      headerGroups: X-Forwarded-Groups
      headerGroupsDelimiter: ','
      inhibitInferRootDN: false

unclassified:
  timestamper:
    allPipelines: true

jobs:
  - script: >
      def pipeline = new File("/etc/jenkins/pipelines/ghaf-demo-nix-build.groovy");
      if (pipeline.exists()) {
        pipelineJob('ghaf-demo-nix-build') {
          definition {
            cps {
              script(pipeline.text)
              sandbox()
            }
          }
        }
      }
